### ISSUE TITLE
how to add margin between two pdf pages 

### ISSUE THREAD

**Issue by aniketsiet50** [ovichowdhury/node-pdf-report#2]

**Comment by ovichowdhury** [comment]
Sorry for late response. You can add a style section in your HTML template like this:
```CSS 
<style>
        @page {
            margin: 10%;
        }
</style>
````
Hopefully, this will resolve the issue.
